### ISSUE TITLE
Error "Not a buffer

### ISSUE THREAD

**Issue by gitlab-pano** [uvasoftware/scanii-lambda#3]
Using the lambda function. These are the errors I am getting:

```
2017-05-23T23:17:20.767Z	f836257c-400d-11e7-a431-bd3743279c79	submitting content for processing
2017-05-23T23:17:20.806Z	f836257c-400d-11e7-a431-bd3743279c79	[TypeError: Not a buffer] 'TypeError: Not a buffer\n at TypeError (native)\n at new Hmac (crypto.js:87:16)\n at Object.Hmac (crypto.js:85:12)\n at generateSignature (/var/task/index.js:67:17)\n at handler.then.processResponse (/var/task/index.js:159:19)\n at handler.then.exports.handler (/var/task/index.js:232:7)'
2017-05-23T23:17:20.809Z	f836257c-400d-11e7-a431-bd3743279c79
{
    "errorMessage": "Not a buffer",
    "errorType": "TypeError",
    "stackTrace": [
        "TypeError (native)",
        "new Hmac (crypto.js:87:16)",
        "Object.Hmac (crypto.js:85:12)",
        "generateSignature (/var/task/index.js:67:17)",
        "handler.then.processResponse (/var/task/index.js:159:19)",
        "handler.then.exports.handler (/var/task/index.js:232:7)"
    ]
}
```
Any ideas?

**Comment by gitlab-pano** [comment]
Okay that turned out to be because when I copied in my Scanni key I did not copy the "secret" section.

Working now. :)
